# Generated by Django 3.2.7 on 2021-09-17 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=80, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sensor', models.CharField(max_length=40, verbose_name='tipo_sensor')),
                ('Descripcion_sensor', models.CharField(max_length=30, verbose_name='Descripcion_sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40, verbose_name='nombres')),
                ('Apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('Usuario', models.CharField(max_length=60, verbose_name='Usuario')),
                ('Contrasena', models.CharField(max_length=30, verbose_name='Contrasena')),
                ('telefono', models.CharField(max_length=30, verbose_name='telefono')),
                ('rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.rol')),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('registro_sensor', models.CharField(max_length=30, verbose_name='registro')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('codigo_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sensores')),
            ],
        ),
    ]
